// export const GET_FORMFILLPAGEITEMS_INPROGRESS =
//   "GET_FORMFILLPAGEITEMS_INPROGRESS";
// export const GET_FORMFILLPAGEITEMS_SUCCESS = "GET_FORMFILLPAGEITEMS_SUCCESS";
// export const GET_FORMFILLPAGEITEMS_FAILURE = "GET_FORMFILLPAGEITEMS_FAILURE";

export const GET_PROFILEPAGEITEMS_INPROGRESS =
  "GET_PROFILEPAGEITEMS_INPROGRESS";
export const GET_PROFILEPAGEITEMS_SUCCESS = "GET_PROFILEPAGEITEMS_SUCCESS";
export const GET_PROFILEPAGEITEMS_FAILURE = "GET_PROFILEPAGEITEMS_FAILURE";

export const GET_FIRSTNAME_INPROGRESS = "GET_FIRSTNAME_INPROGRESS";
export const GET_FIRSTNAME_SUCCESS = "GET_FIRSTNAME_SUCCESS";
export const GET_FIRSTNAME_FAILURE = "GET_FIRSTNAME_FAILURE";
